/**
 *
 */
export enum InputKey {
  Op_A = 'Op_A',
  Op_B = 'Op_B',
  Op_X = 'Op_X',
  Op_Y = 'Op_Y',
  Op_R1 = 'Op_R1',
  Op_R2 = 'Op_R2',
  Op_L1 = 'Op_L1',
  Op_L2 = 'Op_L2',
  Op_Up = 'Op_Up',
  Op_Down = 'Op_Down',
  Op_Left = 'Op_Left',
  Op_Right = 'Op_Right',
  Op_LeftStickUp = 'Op_LeftStickUp',
  Op_LeftStickDown = 'Op_LeftStickDown',
  Op_LeftStickLeft = 'Op_LeftStickLeft',
  Op_LeftStickRight = 'Op_LeftStickRight',
  Op_RightStickUp = 'Op_RightStickUp',
  Op_RightStickDown = 'Op_RightStickDown',
  Op_RightStickLeft = 'Op_RightStickLeft',
  Op_RightStickRight = 'Op_RightStickRight',
  Op_LeftClick = 'Op_LeftClick',
  Op_RightClick = 'Op_RightClick',
  Op_Start = 'Op_Start',
  Op_Select = 'Op_Select',
  Op_Home = 'Op_Home',
  Op_Ok = 'Op_Ok',
  Op_Cancel = 'Op_Cancel',
  Pc_W = 'Pc_W',
  Pc_A = 'Pc_A',
  Pc_S = 'Pc_S',
  Pc_D = 'Pc_D',
  Pc_LeftClick = 'Pc_LeftClick',
  Pc_RightClick = 'Pc_RightClick',
  Pc_Up = 'Pc_Up',
  Pc_Right = 'Pc_Right',
  Pc_Down = 'Pc_Down',
  Pc_Left = 'Pc_Left',
  Pc_MiddleClick = 'Pc_MiddleClick',
  Pc_WheelUp = 'Pc_WheelUp',
  Pc_WhellDown = 'Pc_WhellDown',
  Pc_MousePointer = 'Pc_MousePointer'
}
